/**
 * PDF Export Utility
 *
 * Captures a DOM element and exports it as a PDF document.
 * Uses html2canvas for rendering and jsPDF for PDF generation.
 *
 * Features:
 * - A4 or Letter page size support
 * - Automatic multi-page handling for tall content
 * - Header and footer options
 * - High-quality image rendering
 * - Landscape/Portrait orientation
 */

import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

// =============================================================================
// CONFIGURATION
// =============================================================================

const PAGE_SIZES = {
  a4: { width: 210, height: 297 }, // mm
  letter: { width: 215.9, height: 279.4 }, // mm
};

const DEFAULT_OPTIONS = {
  // Page configuration
  pageSize: "a4",
  orientation: "landscape", // 'portrait' or 'landscape'
  margin: 10, // mm

  // Capture settings
  scale: 2, // Higher = better quality but larger file
  backgroundColor: "#ffffff",

  // Header/Footer
  showHeader: true,
  showFooter: true,
  headerText: "",
  footerText: "Generated by ARKEN AI",

  // Image quality (0-1)
  imageQuality: 0.95,

  // Logging
  logging: false,
};

// =============================================================================
// MAIN EXPORT FUNCTION
// =============================================================================

/**
 * Export a DOM element as a PDF document
 *
 * @param {HTMLElement} element - The DOM element to capture
 * @param {string} filename - The filename (without extension)
 * @param {Object} options - Optional configuration overrides
 * @returns {Promise<jsPDF>} - The jsPDF instance
 */
export async function exportToPDF(element, filename = "export", options = {}) {
  if (!element) {
    throw new Error("No element provided for PDF export");
  }

  const config = { ...DEFAULT_OPTIONS, ...options };

  try {
    // Get page dimensions
    const pageSize = PAGE_SIZES[config.pageSize] || PAGE_SIZES.a4;
    const isLandscape = config.orientation === "landscape";

    const pageWidth = isLandscape ? pageSize.height : pageSize.width;
    const pageHeight = isLandscape ? pageSize.width : pageSize.height;

    // Calculate printable area
    const printWidth = pageWidth - config.margin * 2;
    const printHeight = pageHeight - config.margin * 2;

    // Capture element as canvas
    const canvas = await html2canvas(element, {
      scale: config.scale,
      backgroundColor: config.backgroundColor,
      logging: config.logging,
      useCORS: true,
      allowTaint: true,
      scrollX: 0,
      scrollY: -window.scrollY,
    });

    // Calculate dimensions for PDF
    const imgWidth = printWidth;
    const imgHeight = (canvas.height * printWidth) / canvas.width;

    // Create PDF
    const pdf = new jsPDF({
      orientation: config.orientation,
      unit: "mm",
      format: config.pageSize,
    });

    // Add header if enabled
    const headerHeight = config.showHeader ? 10 : 0;
    const footerHeight = config.showFooter ? 10 : 0;
    const contentHeight = printHeight - headerHeight - footerHeight;

    // Calculate number of pages needed
    const totalPages = Math.ceil(imgHeight / contentHeight);

    // Generate image data URL
    const imgData = canvas.toDataURL("image/png", config.imageQuality);

    // Add pages
    for (let page = 0; page < totalPages; page++) {
      if (page > 0) {
        pdf.addPage();
      }

      // Add header
      if (config.showHeader) {
        addHeader(pdf, config, pageWidth, config.margin);
      }

      // Calculate source and destination rectangles for this page
      const srcY = page * (contentHeight / imgWidth) * canvas.width;
      const srcHeight = Math.min(
        (contentHeight / imgWidth) * canvas.width,
        canvas.height - srcY,
      );

      // Position for this page's content
      const destY = config.margin + headerHeight;
      const destHeight = (srcHeight * imgWidth) / canvas.width;

      // For single-page content, just add the image
      if (totalPages === 1) {
        pdf.addImage(imgData, "PNG", config.margin, destY, imgWidth, imgHeight);
      } else {
        // For multi-page, we need to clip and position
        // This is a simplified approach - just scales to fit
        const yOffset = -page * contentHeight;
        pdf.addImage(
          imgData,
          "PNG",
          config.margin,
          destY + yOffset,
          imgWidth,
          imgHeight,
        );
      }

      // Add footer
      if (config.showFooter) {
        addFooter(pdf, config, pageWidth, pageHeight, page + 1, totalPages);
      }
    }

    // Trigger download
    pdf.save(`${sanitizeFilename(filename)}.pdf`);

    return pdf;
  } catch (error) {
    console.error("[exportToPDF] Error generating PDF:", error);
    throw error;
  }
}

/**
 * Export to PDF with automatic page fitting
 * (Scales content to fit on a single page)
 *
 * @param {HTMLElement} element - The DOM element to capture
 * @param {string} filename - The filename (without extension)
 * @param {Object} options - Optional configuration overrides
 * @returns {Promise<jsPDF>} - The jsPDF instance
 */
export async function exportToPDFSinglePage(
  element,
  filename = "export",
  options = {},
) {
  if (!element) {
    throw new Error("No element provided for PDF export");
  }

  const config = { ...DEFAULT_OPTIONS, ...options };

  try {
    // Get page dimensions
    const pageSize = PAGE_SIZES[config.pageSize] || PAGE_SIZES.a4;
    const isLandscape = config.orientation === "landscape";

    const pageWidth = isLandscape ? pageSize.height : pageSize.width;
    const pageHeight = isLandscape ? pageSize.width : pageSize.height;

    // Calculate printable area
    const printWidth = pageWidth - config.margin * 2;
    const printHeight =
      pageHeight -
      config.margin * 2 -
      (config.showHeader ? 10 : 0) -
      (config.showFooter ? 10 : 0);

    // Capture element as canvas
    const canvas = await html2canvas(element, {
      scale: config.scale,
      backgroundColor: config.backgroundColor,
      logging: config.logging,
      useCORS: true,
      allowTaint: true,
    });

    // Calculate scale to fit on single page
    const widthRatio = printWidth / canvas.width;
    const heightRatio = printHeight / (canvas.height / config.scale);
    const scale = Math.min(widthRatio, heightRatio * config.scale);

    const imgWidth = (canvas.width * scale) / config.scale;
    const imgHeight = (canvas.height * scale) / config.scale;

    // Center on page
    const xOffset = config.margin + (printWidth - imgWidth) / 2;
    const yOffset =
      config.margin +
      (config.showHeader ? 10 : 0) +
      (printHeight - imgHeight) / 2;

    // Create PDF
    const pdf = new jsPDF({
      orientation: config.orientation,
      unit: "mm",
      format: config.pageSize,
    });

    // Add header
    if (config.showHeader) {
      addHeader(pdf, config, pageWidth, config.margin);
    }

    // Add image
    const imgData = canvas.toDataURL("image/png", config.imageQuality);
    pdf.addImage(imgData, "PNG", xOffset, yOffset, imgWidth, imgHeight);

    // Add footer
    if (config.showFooter) {
      addFooter(pdf, config, pageWidth, pageHeight, 1, 1);
    }

    // Trigger download
    pdf.save(`${sanitizeFilename(filename)}.pdf`);

    return pdf;
  } catch (error) {
    console.error("[exportToPDFSinglePage] Error generating PDF:", error);
    throw error;
  }
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Add header to PDF page
 */
function addHeader(pdf, config, pageWidth, margin) {
  const text = config.headerText || "";
  const date = new Date().toLocaleDateString();

  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);

  // Left: Header text
  if (text) {
    pdf.text(text, margin, margin + 5);
  }

  // Right: Date
  pdf.text(date, pageWidth - margin, margin + 5, { align: "right" });

  // Separator line
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, margin + 8, pageWidth - margin, margin + 8);
}

/**
 * Add footer to PDF page
 */
function addFooter(
  pdf,
  config,
  pageWidth,
  pageHeight,
  currentPage,
  totalPages,
) {
  const footerY = pageHeight - config.margin;

  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);

  // Separator line
  pdf.setDrawColor(200, 200, 200);
  pdf.line(config.margin, footerY - 5, pageWidth - config.margin, footerY - 5);

  // Left: Footer text
  pdf.text(config.footerText, config.margin, footerY);

  // Right: Page number
  if (totalPages > 1) {
    pdf.text(
      `Page ${currentPage} of ${totalPages}`,
      pageWidth - config.margin,
      footerY,
      { align: "right" },
    );
  }
}

/**
 * Sanitize filename (remove invalid characters)
 */
function sanitizeFilename(filename) {
  return filename
    .replace(/[<>:"/\\|?*]/g, "_")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .substring(0, 200);
}

// =============================================================================
// EXPORTS
// =============================================================================

export default {
  exportToPDF,
  exportToPDFSinglePage,
};
