/**
 * Report Options Form Component
 *
 * Modal form for configuring detailed report options before generation.
 * Allows users to select which sections to include in the report.
 */

import { useState, useEffect, useCallback } from "react";
import PropTypes from "prop-types";

// =============================================================================
// ICONS
// =============================================================================

const CloseIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-5 w-5"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M6 18L18 6M6 6l12 12"
    />
  </svg>
);

const DocumentIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-6 w-6"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
    />
  </svg>
);

const SparklesIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-4 w-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
    />
  </svg>
);

// =============================================================================
// OPTION DEFINITIONS
// =============================================================================

const REPORT_OPTIONS = [
  {
    key: "include_ai_narratives",
    label: "AI-Generated Narratives",
    description:
      "Executive summary, process descriptions, and observations generated by AI",
    icon: <SparklesIcon />,
    isAI: true,
  },
  {
    key: "include_pfd_image",
    label: "Process Flow Diagram",
    description: "Visual diagram of the process flowsheet",
    icon: "🔄",
  },
  {
    key: "include_stream_tables",
    label: "Stream Data Tables",
    description: "Detailed composition and properties for all streams",
    icon: "📊",
  },
  {
    key: "include_equipment_tables",
    label: "Equipment Data Tables",
    description: "Operating parameters for all equipment units",
    icon: "⚙️",
  },
  {
    key: "include_mass_balance",
    label: "Mass Balance Summary",
    description: "Overall mass balance closure analysis",
    icon: "⚖️",
  },
  {
    key: "include_energy_balance",
    label: "Energy Balance Summary",
    description: "Heat and power flow analysis",
    icon: "🔥",
  },
];

// =============================================================================
// CHECKBOX COMPONENT
// =============================================================================

function OptionCheckbox({ option, checked, onChange }) {
  return (
    <label
      className={`
        flex items-start gap-3 p-3 rounded-lg border cursor-pointer
        transition-all duration-200
        ${
          checked
            ? "bg-blue-50 border-blue-200"
            : "bg-white border-gray-200 hover:border-gray-300"
        }
      `}
    >
      {/* Checkbox */}
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(option.key, e.target.checked)}
        className="mt-0.5 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
      />

      {/* Icon */}
      <div
        className={`
          flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center
          ${option.isAI ? "bg-purple-100 text-purple-600" : "bg-gray-100"}
        `}
      >
        {typeof option.icon === "string" ? (
          <span className="text-base">{option.icon}</span>
        ) : (
          option.icon
        )}
      </div>

      {/* Text */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span
            className={`font-medium ${checked ? "text-gray-900" : "text-gray-700"}`}
          >
            {option.label}
          </span>
          {option.isAI && (
            <span className="px-1.5 py-0.5 text-xs font-medium bg-purple-100 text-purple-700 rounded">
              AI
            </span>
          )}
        </div>
        <p className="text-xs text-gray-500 mt-0.5">{option.description}</p>
      </div>
    </label>
  );
}

OptionCheckbox.propTypes = {
  option: PropTypes.shape({
    key: PropTypes.string.isRequired,
    label: PropTypes.string.isRequired,
    description: PropTypes.string,
    icon: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
    isAI: PropTypes.bool,
  }).isRequired,
  checked: PropTypes.bool.isRequired,
  onChange: PropTypes.func.isRequired,
};

// =============================================================================
// MAIN COMPONENT
// =============================================================================

/**
 * Report Options Form Modal
 *
 * @param {Object} props
 * @param {boolean} props.isOpen - Whether modal is visible
 * @param {Function} props.onClose - Close callback
 * @param {Function} props.onGenerate - Generate callback with selected options
 * @param {Object} props.defaultOptions - Default option values
 */
export default function ReportOptionsForm({
  isOpen,
  onClose,
  onGenerate,
  defaultOptions = {},
}) {
  // Initialize options state
  const [options, setOptions] = useState(() => ({
    include_ai_narratives: true,
    include_pfd_image: true,
    include_stream_tables: true,
    include_equipment_tables: true,
    include_mass_balance: true,
    include_energy_balance: true,
    ...defaultOptions,
  }));

  // Reset options when modal opens
  useEffect(() => {
    if (isOpen) {
      setOptions((prev) => ({
        ...prev,
        ...defaultOptions,
      }));
    }
  }, [isOpen, defaultOptions]);

  // Handle escape key
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e) => {
      if (e.key === "Escape") {
        onClose?.();
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  // Handle option change
  const handleOptionChange = useCallback((key, value) => {
    setOptions((prev) => ({
      ...prev,
      [key]: value,
    }));
  }, []);

  // Handle select all / deselect all
  const handleSelectAll = useCallback((selectAll) => {
    const newOptions = {};
    REPORT_OPTIONS.forEach((opt) => {
      newOptions[opt.key] = selectAll;
    });
    setOptions(newOptions);
  }, []);

  // Handle generate
  const handleGenerate = useCallback(() => {
    onGenerate?.(options);
  }, [options, onGenerate]);

  // Count selected options
  const selectedCount = Object.values(options).filter(Boolean).length;
  const totalCount = REPORT_OPTIONS.length;

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative bg-white rounded-xl shadow-2xl w-full max-w-lg mx-4 max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center text-blue-600">
              <DocumentIcon />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">
                Generate Detailed Report
              </h2>
              <p className="text-sm text-gray-500">
                Select sections to include
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <CloseIcon />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-4">
          {/* Select All / None */}
          <div className="flex items-center justify-between mb-4">
            <span className="text-sm text-gray-600">
              {selectedCount} of {totalCount} sections selected
            </span>
            <div className="flex gap-2">
              <button
                onClick={() => handleSelectAll(true)}
                className="text-xs text-blue-600 hover:text-blue-700 hover:underline"
              >
                Select All
              </button>
              <span className="text-gray-300">|</span>
              <button
                onClick={() => handleSelectAll(false)}
                className="text-xs text-gray-500 hover:text-gray-700 hover:underline"
              >
                Clear All
              </button>
            </div>
          </div>

          {/* Options Grid */}
          <div className="space-y-2">
            {REPORT_OPTIONS.map((option) => (
              <OptionCheckbox
                key={option.key}
                option={option}
                checked={options[option.key] || false}
                onChange={handleOptionChange}
              />
            ))}
          </div>

          {/* AI Note */}
          {options.include_ai_narratives && (
            <div className="mt-4 p-3 bg-purple-50 border border-purple-100 rounded-lg">
              <p className="text-xs text-purple-700">
                <strong>Note:</strong> AI narratives may take 15-30 seconds to
                generate. The report will include executive summary, equipment
                descriptions, and observations.
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-100 bg-gray-50 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded-lg font-medium transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleGenerate}
            disabled={selectedCount === 0}
            className={`
              px-6 py-2 rounded-lg font-medium transition-colors
              ${
                selectedCount === 0
                  ? "bg-gray-200 text-gray-400 cursor-not-allowed"
                  : "bg-blue-600 text-white hover:bg-blue-700"
              }
            `}
          >
            Generate Report
          </button>
        </div>
      </div>
    </div>
  );
}

ReportOptionsForm.propTypes = {
  isOpen: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
  onGenerate: PropTypes.func.isRequired,
  defaultOptions: PropTypes.object,
};
